# ~/.config/starhip.toml

# Use custom format
format = """$shell| $username | $directory $git_branch
> """

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = true

[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style)"
disabled = false
show_always = true

[git_branch]
format = "| on $branch"
truncation_length = 15
truncation_symbol = "..."

[shell]
disabled = false

[directory]
truncation_length = 3
truncate_to_repo = false
